name: Diamond Approach - Folsom - Sacramento - CA
favicon: null
layout_spectrum: 0.1916329578962177
typography_spectrum: 0.7011302663013339
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7306352634914219
  lightness: 0.8391892246436328
  saturation: 0.6791264354251325
  rhythmicContrast: 0.8471922578755766
purpose: []
